### ISSUE TITLE
Typo in Log

### ISSUE THREAD

**Issue by ljasdf** [Toby222/SharkGame#17]
After completing a transaction (I forgot which) in the "turbulent" world, the log says "Results still inconclusive! Unsurpsingly..." and the typo was in it. Consider changing to suprisingly.

**Comment by ljasdf** [comment]
![2023-10-07](https://github.com/Toby222/SharkGame/assets/92997111/2af688da-f477-4cd0-a204-18a35f60f88a)

**Comment by Toby222** [comment]
Thanks!
