### ISSUE TITLE
UI Suggestion: layout buttons by labeled rows, separated by category

### ISSUE THREAD

**Issue by colbyguan** [Toby222/SharkGame#2]
This suggestion would address 2 small sources of friction:
1. When a new button is researched from Laboratory, it could shift over the location of a button away from where the user recalls the button use to be:

![image](https://user-images.githubusercontent.com/6518677/129293728-5aaaa9e4-1755-4e4c-a94b-e819ae4a834d.png)

2. There is a lot of extra clicking involved with switching between the `homeTabsList` ( `All | Basic | Frenzy | Jobs | Producers | Processing` ) menu. I personally don't use it at all. For example, if I wanted to actively increase my fish output:
    * Click processing + click make sharkonium
    * Click other machines + click a machine
    * Click Producers + click nurse shark
    * Repeat last 3 steps

Here is a basic mockup of what a solution might look like:
![image](https://user-images.githubusercontent.com/6518677/129293960-aa336e39-29f4-4f67-ae93-be2fdf7402c3.png)

**Comment by spencers145** [comment]
This idea has some definitive merit, though care would have to be taken to not overuse vertical screen-space. I'll see about adding it to replace or supplement the category switching. It would take a good deal of effort to implement this, though. I'll hold off until the shrouded update is released before potentially tackling this feature.
