### ISSUE TITLE
UI Suggestion: indicator that Laboratory research is available to be purchased

### ISSUE THREAD

**Issue by colbyguan** [Toby222/SharkGame#3]
I assume I'm not alone amongst the gamers in switching between the home tab and the Laboratory tab a lot to check if a research can be purchased. Some form of indicator would be lovely!

Example:
![image](https://user-images.githubusercontent.com/6518677/129294706-4eb517ce-7eea-4cf8-b4fe-af3febd5b969.png)

**Comment by spencers145** [comment]
After much internal deliberation, I think I'll implement something along the lines of this in the coming patches. It'll probably be more useful than not.
